<?php

namespace App\Controller\Admin;

use App\Entity\Estate;
use App\Form\EstateType;
use App\Repository\EstateRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/estate")
 */
class EstateController extends AbstractController
{
    /**
     * @Route("/", name="admin_estate_index", methods={"GET"})
     */
    public function index(EstateRepository $estateRepository): Response
    {
        return $this->render('admin/estate/index.html.twig', [
            'estates' => $estateRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="admin_estate_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $estate = new Estate();
        $form = $this->createForm(EstateType::class, $estate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            //------------------Image Upload--------------//
            /** @var file $flie */
            $file = $form['image']->getData();
            if ($file) {
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
        
            
            // Move the file to the directory where brochures are stored
            try{
                $file -> move(
                    $this->getParameter('images_directory'), // in Service.yaml defined images directory
                    $fileName
                );

            }
            catch(FileException $e){
                //..handle exception if something happens during file upload
            }
            $estate->setImage($fileName);
        }
         //------------------Image Upload--------------//

            $entityManager->persist($estate);
            $entityManager->flush();

            return $this->redirectToRoute('admin_estate_index');
        }

        return $this->render('admin/estate/new.html.twig', [
            'estate' => $estate,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_estate_show", methods={"GET"})
     */
    public function show(Estate $estate): Response
    {
        return $this->render('admin/estate/show.html.twig', [
            'estate' => $estate,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_estate_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Estate $estate): Response
    {
        $form = $this->createForm(EstateType::class, $estate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
             //------------------Image Upload--------------//
            /** @var file $flie */
            $file = $form['image']->getData();
            if ($file) {
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
        
            
            // Move the file to the directory where brochures are stored
            try{
                $file -> move(
                    $this->getParameter('images_directory'), // in Service.yaml defined images directory
                    $fileName
                );

            }
            catch(FileException $e){
                //..handle exception if something happens during file upload
            }
            $estate->setImage($fileName);
        }
         //------------------Image Upload--------------//
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_estate_index');
        }

        return $this->render('admin/estate/edit.html.twig', [
            'estate' => $estate,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_estate_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Estate $estate): Response
    {
        if ($this->isCsrfTokenValid('delete'.$estate->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($estate);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_estate_index');
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
